// Generated by CoffeeScript 1.4.0
(function() {
  var arrayToCsv;

  arrayToCsv = function(fields, array) {
    var csv, item, lines;
    csv = function(raw) {
      var field, o;
      o = JSON.parse(raw);
      return ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = fields.length; _i < _len; _i++) {
          field = fields[_i];
          _results.push(o[field] || '');
        }
        return _results;
      })()).join(',');
    };
    lines = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        item = array[_i];
        _results.push(csv(item));
      }
      return _results;
    })();
    return "" + (fields.join(',')) + "\n" + (lines.join('\n'));
  };

  process.on('message', function(message) {
    var csvItems;
    csvItems = arrayToCsv(message.fields, message.data);
    process.send(csvItems);
    return process.exit();
  });

  exports.arrayToCsv = arrayToCsv;

}).call(this);
