// Generated by CoffeeScript 1.4.0
(function() {

  process.on('message', function(message) {
    var csv, csvItems, item;
    csv = function(raw) {
      var field, o;
      o = JSON.parse(raw);
      return ((function() {
        var _i, _len, _ref, _results;
        _ref = message.fields;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          field = _ref[_i];
          _results.push(o[field] || '');
        }
        return _results;
      })()).join(',');
    };
    csvItems = (function() {
      var _i, _len, _ref, _results;
      _ref = message.data;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _results.push(csv(item));
      }
      return _results;
    })();
    process.send(csvItems);
    return process.exit();
  });

}).call(this);
